//types
import type { Metadata } from "next";
//styles
import { Inter } from "next/font/google";
import "./globals.css";
//components
import Navbar from "@/components/ui_elements/navbar";
import Footer from "@/components/ui_elements/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
